"""The 16-stage workflow: stage enum, explicit DAG and readiness rules."""

from __future__ import annotations

from enum import Enum


class Stage(str, Enum):
    INPUT_AUDIT = "INPUT_AUDIT"
    LIMIT_IMPACT_ANALYSIS = "LIMIT_IMPACT_ANALYSIS"
    PHYSICAL_FEASIBILITY = "PHYSICAL_FEASIBILITY"
    ARCHITECTURE_SCREENING = "ARCHITECTURE_SCREENING"
    IDEAL_ACOUSTIC_OPTIMIZATION = "IDEAL_ACOUSTIC_OPTIMIZATION"
    FOLD_TOPOLOGY_GENERATION = "FOLD_TOPOLOGY_GENERATION"
    FOLD_GEOMETRY_VALIDATION = "FOLD_GEOMETRY_VALIDATION"
    ONE_DIMENSIONAL_SIMULATION = "ONE_DIMENSIONAL_SIMULATION"
    FOLD_AWARE_SIMULATION = "FOLD_AWARE_SIMULATION"
    THREE_DIMENSIONAL_VERIFICATION = "THREE_DIMENSIONAL_VERIFICATION"
    STRUCTURAL_SCREENING = "STRUCTURAL_SCREENING"
    MANUFACTURING_TRANSFORMATION = "MANUFACTURING_TRANSFORMATION"
    CONSTRAINT_SENSITIVITY = "CONSTRAINT_SENSITIVITY"
    INDEPENDENT_CRITIQUE = "INDEPENDENT_CRITIQUE"
    FINAL_COMPARISON = "FINAL_COMPARISON"
    REPORT_AND_EXPORT = "REPORT_AND_EXPORT"


STAGE_ORDER: tuple[Stage, ...] = (
    Stage.INPUT_AUDIT,
    Stage.LIMIT_IMPACT_ANALYSIS,
    Stage.PHYSICAL_FEASIBILITY,
    Stage.ARCHITECTURE_SCREENING,
    Stage.IDEAL_ACOUSTIC_OPTIMIZATION,
    Stage.FOLD_TOPOLOGY_GENERATION,
    Stage.FOLD_GEOMETRY_VALIDATION,
    Stage.ONE_DIMENSIONAL_SIMULATION,
    Stage.FOLD_AWARE_SIMULATION,
    Stage.THREE_DIMENSIONAL_VERIFICATION,
    Stage.STRUCTURAL_SCREENING,
    Stage.MANUFACTURING_TRANSFORMATION,
    Stage.CONSTRAINT_SENSITIVITY,
    Stage.INDEPENDENT_CRITIQUE,
    Stage.FINAL_COMPARISON,
    Stage.REPORT_AND_EXPORT,
)

# Direct prerequisites (the DAG edges).
PREREQUISITES: dict[Stage, tuple[Stage, ...]] = {
    Stage.INPUT_AUDIT: (),
    Stage.LIMIT_IMPACT_ANALYSIS: (Stage.INPUT_AUDIT,),
    Stage.PHYSICAL_FEASIBILITY: (Stage.INPUT_AUDIT,),
    Stage.ARCHITECTURE_SCREENING: (Stage.PHYSICAL_FEASIBILITY, Stage.LIMIT_IMPACT_ANALYSIS),
    Stage.IDEAL_ACOUSTIC_OPTIMIZATION: (Stage.ARCHITECTURE_SCREENING,),
    Stage.FOLD_TOPOLOGY_GENERATION: (Stage.IDEAL_ACOUSTIC_OPTIMIZATION,),
    Stage.FOLD_GEOMETRY_VALIDATION: (Stage.FOLD_TOPOLOGY_GENERATION,),
    Stage.ONE_DIMENSIONAL_SIMULATION: (Stage.IDEAL_ACOUSTIC_OPTIMIZATION,),
    Stage.FOLD_AWARE_SIMULATION: (Stage.FOLD_GEOMETRY_VALIDATION, Stage.ONE_DIMENSIONAL_SIMULATION),
    Stage.THREE_DIMENSIONAL_VERIFICATION: (Stage.FOLD_AWARE_SIMULATION,),
    Stage.STRUCTURAL_SCREENING: (Stage.FOLD_GEOMETRY_VALIDATION,),
    Stage.MANUFACTURING_TRANSFORMATION: (Stage.FOLD_GEOMETRY_VALIDATION, Stage.STRUCTURAL_SCREENING),
    Stage.CONSTRAINT_SENSITIVITY: (Stage.ONE_DIMENSIONAL_SIMULATION,),
    Stage.INDEPENDENT_CRITIQUE: (Stage.FOLD_AWARE_SIMULATION, Stage.MANUFACTURING_TRANSFORMATION,
                                 Stage.CONSTRAINT_SENSITIVITY),
    Stage.FINAL_COMPARISON: (Stage.INDEPENDENT_CRITIQUE,),
    Stage.REPORT_AND_EXPORT: (Stage.FINAL_COMPARISON,),
}

# Stages that a run may legitimately skip (e.g. no BEM solver installed).
OPTIONAL_STAGES: frozenset = frozenset({
    Stage.THREE_DIMENSIONAL_VERIFICATION,
})


def prerequisites(stage: Stage) -> tuple[Stage, ...]:
    return PREREQUISITES[stage]


def ready(stage: Stage, stages: dict) -> bool:
    """True when every prerequisite has status 'passed' (or 'skipped' if optional)."""
    for pre in PREREQUISITES[stage]:
        st = str(stages.get(pre, {}).get("status", "pending"))
        if st == "passed":
            continue
        if st == "skipped" and pre in OPTIONAL_STAGES:
            continue
        return False
    return True
